services:
  app:
    build: .
    container_name: generic
    image: generic
    volumes:
      - .:/home/python/app
    environment:
      - PYTHONPATH=/home/python/app

      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5433
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

    tty: true
    ports:
      - 8000:8000


  postgres_test:
    image: ankane/pgvector
    container_name: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
